### ISSUE TITLE
addressbook-level 4: imports from com.google cannot be resolved 

### ISSUE THREAD

**Issue by alexawangzi** [nus-cs2103-AY1718S2/forum#20] opened 2018-03-03 01:00 UTC
Hi all,

I am facing this issue that I cannot resolve, would appreciate your advice.
As shown in the screenshots, the imports from com.google cannot be resolved when I open the gradle project.

![screenshot 205](https://user-images.githubusercontent.com/28506646/36928396-8f0ba83a-1ec0-11e8-94c0-b9bf942ba956.png)
![screenshot 203](https://user-images.githubusercontent.com/28506646/36928397-8f3ecc7e-1ec0-11e8-8cae-634efb373e85.png)
![screenshot 204](https://user-images.githubusercontent.com/28506646/36928398-8f9539b0-1ec0-11e8-8579-df3da9c859f7.png)

I have tried invalidate/restart intelliJ and clear the gradle caches but that did not solve the problem. 
Any idea on why is this happening?
Thank you.

Regards,
Wang Zi

**Comment by Zhiyuan-Amos** [comment] 2018-03-03 03:16
Hi! Can you try clicking on the 2 blue color circular arrows (the first button, directly below "Gradle Projects") and see if it works? That button refreshes your gradle project.

![image](https://user-images.githubusercontent.com/19281514/36930018-3654bd4e-1ed4-11e8-9076-aa1388be4be9.png)

If that doesn't work, can you give more details on how this issue happened? Did you follow the setting up instructions in the [Developer Guide](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc)? :)

**Comment by okkhoy** [comment] 2018-03-03 03:44
BTW., did you also do step 8 in the dev guide:
> Open a console and run the command gradlew processResources (Mac/Linux: ./gradlew processResources). It should finish with the BUILD SUCCESSFUL message.

**Comment by alexawangzi** [comment] 2018-03-03 13:17
@Zhiyuan-Amos  Thank you for the advice but the issue persists after I refreshes the project multiple times. The probelm surfaced when I first tried opening the project. I followed the Developer guide in setting up.

@okkhoy  Yes I did. I first run inside IntelliJ (screenshot on the left), but the issue persists. Then I tried running from cmd (screeshots on the right), but that did not solve the problem either.
![image](https://user-images.githubusercontent.com/28506646/36934627-9ee2adb4-1f27-11e8-946c-0f266d850831.png)

**Comment by okkhoy** [comment] 2018-03-03 14:27
Ok. One of the things that can lead to this weird situation is when the downloaded jar is corrupt. (Happened to me in a different project).

I am on a Linux machine, so you need to find Windows equivalent of the paths. Start at `C:\Users\<you>\AppData\Local`; if it is not here, then you have a longer task cut out! :man_facepalming: 

On my machine, I have a `~/.gradle/caches/modules-2/files-2.1/` directory where I can see `org.fxmisc.easybind` and `com.google.*` folders. This is where the downloaded gradle JARs will be (deep inside the folders).
Find the equivalent of this and delete both `org.fxmisc.easybind` and any other offending packages.

Next, open the folder where you have cloned AB-L4 on the command line and run a `gradlew clean build`. After this, open the IDE and check if the problem is resolved.

What we are doing: we are trying to force gradle to re-download the offending package here.

Hope this helps! :crossed_fingers:

**Comment by alexawangzi** [comment] 2018-03-06 05:53
@okkhoy 
This worked! Thank you very much...

**Comment by okkhoy** [comment] 2018-03-06 06:06
Great! Will close the issue!

**Closed as completed by okkhoy** 2018-03-06 06:06 UTC
Labels: type-HelpRequest
